"""initial schema + PostGIS

Enables the PostGIS extension (required before any GEOGRAPHY column is created)
and then builds the full schema from the SQLAlchemy metadata. GeoAlchemy2
registers DDL hooks that additionally create GiST spatial indexes on the
geography columns during table creation.

Revision ID: 0001
Revises:
Create Date: 2026-07-20
"""
from alembic import op

from app.db.base import Base
import app.models  # noqa: F401  (registers all tables on Base.metadata)

# The revision chain. down_revision = None marks this as the first migration —
# Alembic follows these links to work out what order to apply things in.
revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create the whole schema from scratch."""
    bind = op.get_bind()

    # MUST come before create_all. The depots and orders tables have GEOGRAPHY
    # columns, and that type does not exist in a stock Postgres database — it is
    # provided by PostGIS. Creating the tables first fails with
    # `type "geography" does not exist`.
    #
    # IF NOT EXISTS so this is safe on a database where the extension is already
    # installed (a managed host may pre-enable it).
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    # Build every table straight from the ORM metadata, rather than a list of
    # op.create_table() calls.
    #
    # Two reasons this is the right choice for the FIRST migration:
    #   * it cannot drift from the models — the models are the source
    #   * GeoAlchemy2 hooks into create_all and issues the GiST index DDL for
    #     the geography columns, which is why those indexes appear nowhere in
    #     this file
    #
    # It is NOT a pattern for later migrations: create_all only ever creates
    # what the models currently say, so it cannot express an alteration. Every
    # subsequent revision should be a normal autogenerated op.* script.
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    """Drop everything. **Destroys all data.**

    Correct as the inverse of "create the initial schema" — the only prior state
    is an empty database — but it is not a rollback to run against anything you
    care about.

    Note the PostGIS extension is deliberately NOT dropped: other schemas in the
    same database may depend on it, and removing a shared extension on the way
    out would be an unpleasant surprise.
    """
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
